include ../config.mk

BIN = ranges htoi squeeze any setbits bitcount lower

include ../build.mk

# ch2
ranges: ranges.o
htoi: htoi.o
squeeze: squeeze.o
any: any.o
setbits: setbits.o
bitcount: bitcount.o
lower: lower.o
