include ../config.mk

BIN = binsearch escape expand itoa itob itoa-pad

include ../build.mk

# ch3
binsearch: binsearch.o
escape: escape.o
expand: expand.o
itoa: itoa.o
itob: itob.o
itoa-pad: itoa-pad.o
