include ../config.mk

BIN = hello fahr celsius fahr-rev iseof eof blank-count blank-dedup \
	blank-vis word-per-line word-len-hist char-freq-hist fahr-fun\
	detab entab uncomment

include ../build.mk

# ch1
hello: hello.o
fahr: fahr.o
celsius: celsius.o
fahr-rev: fahr-rev.o
iseof: iseof.o
eof: eof.o
blank-count: blank-count.o
blank-dedup: blank-dedup.o
blank-vis: blank-vis.o
word-per-line: word-per-line.o
word-len-hist: word-len-hist.o
char-freq-hist: char-freq-hist.o
fahr-fun: fahr-fun.o
detab: detab.o
entab: entab.o
uncomment: uncomment.o
